In [23]:
import pandas as pd
df = pd.read_csv("Uber+Drives+2016.csv")

In [3]:
df

START_DATE*         END_DATE* CATEGORY*            START*  \
0       1/1/2016 21:11    1/1/2016 21:17  Business       Fort Pierce   
1        1/2/2016 1:25     1/2/2016 1:37  Business       Fort Pierce   
2       1/2/2016 20:25    1/2/2016 20:38  Business       Fort Pierce   
3       1/5/2016 17:31    1/5/2016 17:45  Business       Fort Pierce   
4       1/6/2016 14:42    1/6/2016 15:49  Business       Fort Pierce   
...                ...               ...       ...               ...   
1151  12/31/2016 13:24  12/31/2016 13:42  Business           Kar?chi   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1153  12/31/2016 21:32  12/31/2016 21:50  Business        Katunayake   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*         PURPOSE*  
0          Fort Pierce      5.1   Meal/Entertain  
1          Fort Pierce      5.0              NaN  
2          Fort Pierce      4.8  Errand/Supplies  
3          Fort Pierce      4.7          Meeting  
4      West Palm Beach     63.7   Customer Visit  
...                ...      ...              ...  
1151  Unknown Location      3.9   Temporary Site  
1152  Unknown Location     16.2          Meeting  
1153           Gampaha      6.4   Temporary Site  
1154         Ilukwatta     48.2   Temporary Site  
1155               NaN  12204.7              NaN  

[1156 rows x 7 columns]

In [24]:
type(df)

pandas.core.frame.DataFrame

In [25]:
df.dtypes

START_DATE*     object
END_DATE*       object
CATEGORY*       object
START*          object
STOP*           object
MILES*         float64
PURPOSE*        object
dtype: object

In [26]:
df.head(10)

START_DATE*        END_DATE* CATEGORY*           START*  \
0   1/1/2016 21:11   1/1/2016 21:17  Business      Fort Pierce   
1    1/2/2016 1:25    1/2/2016 1:37  Business      Fort Pierce   
2   1/2/2016 20:25   1/2/2016 20:38  Business      Fort Pierce   
3   1/5/2016 17:31   1/5/2016 17:45  Business      Fort Pierce   
4   1/6/2016 14:42   1/6/2016 15:49  Business      Fort Pierce   
5   1/6/2016 17:15   1/6/2016 17:19  Business  West Palm Beach   
6   1/6/2016 17:30   1/6/2016 17:35  Business  West Palm Beach   
7   1/7/2016 13:27   1/7/2016 13:33  Business             Cary   
8   1/10/2016 8:05   1/10/2016 8:25  Business             Cary   
9  1/10/2016 12:17  1/10/2016 12:44  Business          Jamaica   

             STOP*  MILES*         PURPOSE*  
0      Fort Pierce     5.1   Meal/Entertain  
1      Fort Pierce     5.0              NaN  
2      Fort Pierce     4.8  Errand/Supplies  
3      Fort Pierce     4.7          Meeting  
4  West Palm Beach    63.7   Customer Visit  
5  West Palm Beach     4.3   Meal/Entertain  
6       Palm Beach     7.1          Meeting  
7             Cary     0.8          Meeting  
8      Morrisville     8.3          Meeting  
9         New York    16.5   Customer Visit

In [27]:
df.shape

(1156, 7)

In [28]:
temp = pd.DataFrame({"A":["1","2","3"],"B":[10,12,13],"C":["12-06-2012","13-06-2015","12-05-2019"]})

In [29]:
temp["C"]=pd.to_datetime(temp["C"])
temp
temp.dtypes

C:\Users\admin\AppData\Local\Temp\ipykernel_5600\2758699173.py:1: UserWarning: Parsing '13-06-2015' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  temp["C"]=pd.to_datetime(temp["C"])


A            object
B             int64
C    datetime64[ns]
dtype: object

In [30]:
pd.to_datetime(["2016-11-16","abc"],errors = "coerce")

DatetimeIndex(['2016-11-16', 'NaT'], dtype='datetime64[ns]', freq=None)

In [31]:
temp["A"] = pd.to_numeric(temp["A"])

In [32]:
temp.dtypes

A             int64
B             int64
C    datetime64[ns]
dtype: object

In [33]:
df.describe(include = "all")

START_DATE*        END_DATE* CATEGORY* START* STOP*        MILES*  \
count              1156             1155      1155   1155  1155   1156.000000   
unique             1155             1154         2    177   188           NaN   
top     6/28/2016 23:34  6/28/2016 23:59  Business   Cary  Cary           NaN   
freq                  2                2      1078    201   203           NaN   
mean                NaN              NaN       NaN    NaN   NaN     21.115398   
std                 NaN              NaN       NaN    NaN   NaN    359.299007   
min                 NaN              NaN       NaN    NaN   NaN      0.500000   
25%                 NaN              NaN       NaN    NaN   NaN      2.900000   
50%                 NaN              NaN       NaN    NaN   NaN      6.000000   
75%                 NaN              NaN       NaN    NaN   NaN     10.400000   
max                 NaN              NaN       NaN    NaN   NaN  12204.700000   

       PURPOSE*  
count       653  
unique       10  
top     Meeting  
freq        187  
mean        NaN  
std         NaN  
min         NaN  
25%         NaN  
50%         NaN  
75%         NaN  
max         NaN

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   START_DATE*  1156 non-null   object 
 1   END_DATE*    1155 non-null   object 
 2   CATEGORY*    1155 non-null   object 
 3   START*       1155 non-null   object 
 4   STOP*        1155 non-null   object 
 5   MILES*       1156 non-null   float64
 6   PURPOSE*     653 non-null    object 
dtypes: float64(1), object(6)
memory usage: 63.3+ KB


In [35]:
df["START*"].value_counts().head()

Cary                201
Unknown Location    148
Morrisville          85
Whitebridge          68
Islamabad            57
Name: START*, dtype: int64

# Select/indexing

In [36]:
df.iloc[0:5,0:6]

START_DATE*       END_DATE* CATEGORY*       START*            STOP*  \
0  1/1/2016 21:11  1/1/2016 21:17  Business  Fort Pierce      Fort Pierce   
1   1/2/2016 1:25   1/2/2016 1:37  Business  Fort Pierce      Fort Pierce   
2  1/2/2016 20:25  1/2/2016 20:38  Business  Fort Pierce      Fort Pierce   
3  1/5/2016 17:31  1/5/2016 17:45  Business  Fort Pierce      Fort Pierce   
4  1/6/2016 14:42  1/6/2016 15:49  Business  Fort Pierce  West Palm Beach   

   MILES*  
0     5.1  
1     5.0  
2     4.8  
3     4.7  
4    63.7

In [37]:
df.iloc[0:5,[0,3]]

START_DATE*       START*
0  1/1/2016 21:11  Fort Pierce
1   1/2/2016 1:25  Fort Pierce
2  1/2/2016 20:25  Fort Pierce
3  1/5/2016 17:31  Fort Pierce
4  1/6/2016 14:42  Fort Pierce

In [38]:
jay = df.iloc[0:4]
print(df.shape)
jay.shape

(1156, 7)


(4, 7)

In [39]:
df.loc[:,["START*","STOP*"]]

START*             STOP*
0          Fort Pierce       Fort Pierce
1          Fort Pierce       Fort Pierce
2          Fort Pierce       Fort Pierce
3          Fort Pierce       Fort Pierce
4          Fort Pierce   West Palm Beach
...                ...               ...
1151           Kar?chi  Unknown Location
1152  Unknown Location  Unknown Location
1153        Katunayake           Gampaha
1154           Gampaha         Ilukwatta
1155               NaN               NaN

[1156 rows x 2 columns]

In [40]:
df[["START*","STOP*"]]

START*             STOP*
0          Fort Pierce       Fort Pierce
1          Fort Pierce       Fort Pierce
2          Fort Pierce       Fort Pierce
3          Fort Pierce       Fort Pierce
4          Fort Pierce   West Palm Beach
...                ...               ...
1151           Kar?chi  Unknown Location
1152  Unknown Location  Unknown Location
1153        Katunayake           Gampaha
1154           Gampaha         Ilukwatta
1155               NaN               NaN

[1156 rows x 2 columns]

In [41]:
abc = df.loc[:,["START*"]]

In [42]:
abc

START*
0          Fort Pierce
1          Fort Pierce
2          Fort Pierce
3          Fort Pierce
4          Fort Pierce
...                ...
1151           Kar?chi
1152  Unknown Location
1153        Katunayake
1154           Gampaha
1155               NaN

[1156 rows x 1 columns]

In [43]:
df.loc[:,("START*","STOP*")]

START*             STOP*
0          Fort Pierce       Fort Pierce
1          Fort Pierce       Fort Pierce
2          Fort Pierce       Fort Pierce
3          Fort Pierce       Fort Pierce
4          Fort Pierce   West Palm Beach
...                ...               ...
1151           Kar?chi  Unknown Location
1152  Unknown Location  Unknown Location
1153        Katunayake           Gampaha
1154           Gampaha         Ilukwatta
1155               NaN               NaN

[1156 rows x 2 columns]

In [44]:
df.loc[0:4,["START_DATE*","MILES*"]]
df.columns

Index(['START_DATE*', 'END_DATE*', 'CATEGORY*', 'START*', 'STOP*', 'MILES*',
       'PURPOSE*'],
      dtype='object')

In [45]:
df.loc[df["MILES*"] > 10]

START_DATE*         END_DATE* CATEGORY*            START*  \
4       1/6/2016 14:42    1/6/2016 15:49  Business       Fort Pierce   
9      1/10/2016 12:17   1/10/2016 12:44  Business           Jamaica   
10     1/10/2016 15:08   1/10/2016 15:51  Business          New York   
22     1/12/2016 16:02   1/12/2016 17:00  Business          New York   
23     1/13/2016 13:54   1/13/2016 14:07  Business          Downtown   
...                ...               ...       ...               ...   
1134  12/29/2016 11:28  12/29/2016 12:00  Business  Unknown Location   
1144  12/29/2016 23:14  12/29/2016 23:47  Business  Unknown Location   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*        PURPOSE*  
4      West Palm Beach     63.7  Customer Visit  
9             New York     16.5  Customer Visit  
10              Queens     10.8         Meeting  
22       Queens County     15.1         Meeting  
23             Gulfton     11.2         Meeting  
...                ...      ...             ...  
1134           Kar?chi     11.9  Meal/Entertain  
1144           Kar?chi     12.9         Meeting  
1152  Unknown Location     16.2         Meeting  
1154         Ilukwatta     48.2  Temporary Site  
1155               NaN  12204.7             NaN  

[316 rows x 7 columns]

In [46]:
df2 = df[df["MILES*"]>10]

In [47]:
df2

START_DATE*         END_DATE* CATEGORY*            START*  \
4       1/6/2016 14:42    1/6/2016 15:49  Business       Fort Pierce   
9      1/10/2016 12:17   1/10/2016 12:44  Business           Jamaica   
10     1/10/2016 15:08   1/10/2016 15:51  Business          New York   
22     1/12/2016 16:02   1/12/2016 17:00  Business          New York   
23     1/13/2016 13:54   1/13/2016 14:07  Business          Downtown   
...                ...               ...       ...               ...   
1134  12/29/2016 11:28  12/29/2016 12:00  Business  Unknown Location   
1144  12/29/2016 23:14  12/29/2016 23:47  Business  Unknown Location   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*        PURPOSE*  
4      West Palm Beach     63.7  Customer Visit  
9             New York     16.5  Customer Visit  
10              Queens     10.8         Meeting  
22       Queens County     15.1         Meeting  
23             Gulfton     11.2         Meeting  
...                ...      ...             ...  
1134           Kar?chi     11.9  Meal/Entertain  
1144           Kar?chi     12.9         Meeting  
1152  Unknown Location     16.2         Meeting  
1154         Ilukwatta     48.2  Temporary Site  
1155               NaN  12204.7             NaN  

[316 rows x 7 columns]

In [48]:
df.loc[df["START*"]=="New York",["MILES*","START*"]].head()

MILES*    START*
10     10.8  New York
22     15.1  New York
106    13.0  New York
423    16.3  New York

In [49]:
my_rides = df[df["START*"].isin(["Cary","New York"])]

In [50]:
my_rides.iloc[0:5,:]
df
my_rides

START_DATE*         END_DATE* CATEGORY*    START*          STOP*  \
7       1/7/2016 13:27    1/7/2016 13:33  Business      Cary           Cary   
8       1/10/2016 8:05    1/10/2016 8:25  Business      Cary    Morrisville   
10     1/10/2016 15:08   1/10/2016 15:51  Business  New York         Queens   
22     1/12/2016 16:02   1/12/2016 17:00  Business  New York  Queens County   
28     1/15/2016 11:43   1/15/2016 12:03  Business      Cary         Durham   
...                ...               ...       ...       ...            ...   
1049  12/13/2016 20:20  12/13/2016 20:29  Business      Cary           Cary   
1050  12/14/2016 16:52  12/14/2016 17:10  Business      Cary           Cary   
1051  12/14/2016 17:22  12/14/2016 17:34  Business      Cary           Cary   
1052  12/14/2016 17:50  12/14/2016 18:00  Business      Cary    Morrisville   
1054  12/15/2016 14:20  12/15/2016 14:54  Business      Cary    Morrisville   

      MILES*        PURPOSE*  
7        0.8         Meeting  
8        8.3         Meeting  
10      10.8         Meeting  
22      15.1         Meeting  
28      10.4  Meal/Entertain  
...      ...             ...  
1049     4.1  Meal/Entertain  
1050     3.4             NaN  
1051     3.3             NaN  
1052     3.0  Meal/Entertain  
1054    10.6         Meeting  

[205 rows x 7 columns]

In [51]:
df3 = df[(df["MILES*"] > 10) & (df["START*"].isin(["Cary","Morrisvile"]))]
df3.reset_index(inplace = True)
df3

index       START_DATE*         END_DATE* CATEGORY* START*          STOP*  \
0      28   1/15/2016 11:43   1/15/2016 12:03  Business   Cary         Durham   
1      34   1/20/2016 10:36   1/20/2016 11:11  Business   Cary        Raleigh   
2      46   1/27/2016 10:19   1/27/2016 10:48  Business   Cary        Raleigh   
3      50   1/28/2016 12:28   1/28/2016 13:00  Business   Cary        Raleigh   
4      55   1/29/2016 11:43   1/29/2016 12:03  Business   Cary         Durham   
5      61    2/1/2016 10:35    2/1/2016 11:15  Business   Cary    Chapel Hill   
6      74    2/5/2016 11:47    2/5/2016 12:07  Business   Cary         Durham   
7      76    2/6/2016 16:20    2/6/2016 16:53  Business   Cary        Raleigh   
8      91   2/11/2016 16:28   2/11/2016 17:10  Business   Cary        Raleigh   
9     164   2/26/2016 11:35   2/26/2016 11:59  Business   Cary         Durham   
10    185    3/4/2016 11:46    3/4/2016 12:06  Business   Cary         Durham   
11    187    3/4/2016 13:40    3/4/2016 14:09  Business   Cary        Raleigh   
12    200     3/7/2016 9:23     3/7/2016 9:47  Business   Cary        Raleigh   
13    268   3/25/2016 13:24   3/25/2016 16:22  Business   Cary          Latta   
14    304    4/8/2016 12:30    4/8/2016 12:48  Business   Cary         Durham   
15    307    4/8/2016 14:43    4/8/2016 15:20  Business   Cary        Raleigh   
16    314    4/14/2016 7:29    4/14/2016 8:09  Business   Cary  Holly Springs   
17    316   4/15/2016 11:36   4/15/2016 12:07  Business   Cary        Raleigh   
18    323    4/22/2016 8:25    4/22/2016 9:04  Business   Cary        Raleigh   
19    325   4/22/2016 12:08   4/22/2016 12:28  Business   Cary         Durham   
20    334   4/28/2016 12:09   4/28/2016 12:34  Business   Cary        Raleigh   
21    339   4/29/2016 18:46   4/29/2016 19:18  Business   Cary         Durham   
22    389   5/31/2016 13:54   5/31/2016 14:41  Business   Cary        Raleigh   
23    394    6/3/2016 11:29    6/3/2016 11:49  Business   Cary         Durham   
24    411    6/6/2016 21:41    6/6/2016 22:00  Business   Cary         Durham   
25    413    6/7/2016 21:42    6/7/2016 22:00  Business   Cary         Durham   
26    424   6/10/2016 21:47   6/10/2016 22:04  Business   Cary         Durham   
27    429   6/11/2016 21:45   6/11/2016 22:04  Business   Cary         Durham   
28    457   6/21/2016 15:39   6/21/2016 16:08  Business   Cary        Raleigh   
29    490   6/28/2016 20:13   6/28/2016 20:33  Business   Cary         Durham   
30    497   6/29/2016 20:11   6/29/2016 20:29  Business   Cary         Durham   
31    501     7/1/2016 9:34     7/1/2016 9:57  Business   Cary        Raleigh   
32    503    7/1/2016 20:06    7/1/2016 20:24  Business   Cary         Durham   
33    505    7/2/2016 20:18    7/2/2016 20:36  Business   Cary         Durham   
34    513    7/4/2016 20:00    7/4/2016 20:17  Business   Cary         Durham   
35    541   7/13/2016 12:39   7/13/2016 13:20  Personal   Cary    Morrisville   
36    593   7/23/2016 20:17   7/23/2016 20:33  Business   Cary         Durham   
37    609   7/30/2016 17:02   7/30/2016 17:27  Business   Cary         Durham   
38    642    8/9/2016 15:15    8/9/2016 15:36  Business   Cary        Raleigh   
39    644   8/10/2016 16:56   8/10/2016 17:24  Business   Cary         Durham   
40    651   8/11/2016 18:37   8/11/2016 19:29  Business   Cary    Wake Forest   
41    816  10/16/2016 12:52  10/16/2016 13:11  Business   Cary         Durham   
42    822  10/17/2016 15:19  10/17/2016 15:57  Business   Cary        Raleigh   
43    845  10/22/2016 13:26  10/22/2016 14:03  Business   Cary        Raleigh   
44    847   10/23/2016 9:24  10/23/2016 10:05  Business   Cary        Raleigh   
45    851  10/24/2016 14:57  10/24/2016 15:26  Business   Cary         Durham   
46    854  10/25/2016 13:27  10/25/2016 14:08  Business   Cary           Apex   
47    867  10/28/2016 11:34  10/28/2016 11:52  Business   Cary         Durham   
48    869  10/28/2016 15:53  10/28/

In [52]:
df.sort_values(by=["MILES*"],ascending = True).head()

START_DATE*         END_DATE* CATEGORY*      START*       STOP*  \
420     6/8/2016 17:16    6/8/2016 17:18  Business        Soho     Tribeca   
44     1/26/2016 17:27   1/26/2016 17:29  Business        Cary        Cary   
120    2/17/2016 16:38   2/17/2016 16:43  Business  Katunayaka  Katunayaka   
1111   12/25/2016 0:10   12/25/2016 0:14  Business      Lahore      Lahore   
1110  12/24/2016 22:04  12/24/2016 22:09  Business      Lahore      Lahore   

      MILES*         PURPOSE*  
420      0.5  Errand/Supplies  
44       0.5  Errand/Supplies  
120      0.5  Errand/Supplies  
1111     0.6  Errand/Supplies  
1110     0.6  Errand/Supplies

In [53]:
import numpy as np
df["MILES_cat"]=np.where(df["MILES*"]>5,"long trip","short trip")

In [54]:
df

START_DATE*         END_DATE* CATEGORY*            START*  \
0       1/1/2016 21:11    1/1/2016 21:17  Business       Fort Pierce   
1        1/2/2016 1:25     1/2/2016 1:37  Business       Fort Pierce   
2       1/2/2016 20:25    1/2/2016 20:38  Business       Fort Pierce   
3       1/5/2016 17:31    1/5/2016 17:45  Business       Fort Pierce   
4       1/6/2016 14:42    1/6/2016 15:49  Business       Fort Pierce   
...                ...               ...       ...               ...   
1151  12/31/2016 13:24  12/31/2016 13:42  Business           Kar?chi   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1153  12/31/2016 21:32  12/31/2016 21:50  Business        Katunayake   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*         PURPOSE*   MILES_cat  
0          Fort Pierce      5.1   Meal/Entertain   long trip  
1          Fort Pierce      5.0              NaN  short trip  
2          Fort Pierce      4.8  Errand/Supplies  short trip  
3          Fort Pierce      4.7          Meeting  short trip  
4      West Palm Beach     63.7   Customer Visit   long trip  
...                ...      ...              ...         ...  
1151  Unknown Location      3.9   Temporary Site  short trip  
1152  Unknown Location     16.2          Meeting   long trip  
1153           Gampaha      6.4   Temporary Site   long trip  
1154         Ilukwatta     48.2   Temporary Site   long trip  
1155               NaN  12204.7              NaN   long trip  

[1156 rows x 8 columns]

In [55]:
df["Miles_cat"] = np.where(df["MILES*"]>10,"long trip",np.where(df["MILES*"]<5,"short trip",
                                                               "Medium trip"))

In [56]:
df

START_DATE*         END_DATE* CATEGORY*            START*  \
0       1/1/2016 21:11    1/1/2016 21:17  Business       Fort Pierce   
1        1/2/2016 1:25     1/2/2016 1:37  Business       Fort Pierce   
2       1/2/2016 20:25    1/2/2016 20:38  Business       Fort Pierce   
3       1/5/2016 17:31    1/5/2016 17:45  Business       Fort Pierce   
4       1/6/2016 14:42    1/6/2016 15:49  Business       Fort Pierce   
...                ...               ...       ...               ...   
1151  12/31/2016 13:24  12/31/2016 13:42  Business           Kar?chi   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1153  12/31/2016 21:32  12/31/2016 21:50  Business        Katunayake   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*         PURPOSE*   MILES_cat    Miles_cat  
0          Fort Pierce      5.1   Meal/Entertain   long trip  Medium trip  
1          Fort Pierce      5.0              NaN  short trip  Medium trip  
2          Fort Pierce      4.8  Errand/Supplies  short trip   short trip  
3          Fort Pierce      4.7          Meeting  short trip   short trip  
4      West Palm Beach     63.7   Customer Visit   long trip    long trip  
...                ...      ...              ...         ...          ...  
1151  Unknown Location      3.9   Temporary Site  short trip   short trip  
1152  Unknown Location     16.2          Meeting   long trip    long trip  
1153           Gampaha      6.4   Temporary Site   long trip  Medium trip  
1154         Ilukwatta     48.2   Temporary Site   long trip    long trip  
1155               NaN  12204.7              NaN   long trip    long trip  

[1156 rows x 9 columns]

# Groupby

In [57]:
df

START_DATE*         END_DATE* CATEGORY*            START*  \
0       1/1/2016 21:11    1/1/2016 21:17  Business       Fort Pierce   
1        1/2/2016 1:25     1/2/2016 1:37  Business       Fort Pierce   
2       1/2/2016 20:25    1/2/2016 20:38  Business       Fort Pierce   
3       1/5/2016 17:31    1/5/2016 17:45  Business       Fort Pierce   
4       1/6/2016 14:42    1/6/2016 15:49  Business       Fort Pierce   
...                ...               ...       ...               ...   
1151  12/31/2016 13:24  12/31/2016 13:42  Business           Kar?chi   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1153  12/31/2016 21:32  12/31/2016 21:50  Business        Katunayake   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*         PURPOSE*   MILES_cat    Miles_cat  
0          Fort Pierce      5.1   Meal/Entertain   long trip  Medium trip  
1          Fort Pierce      5.0              NaN  short trip  Medium trip  
2          Fort Pierce      4.8  Errand/Supplies  short trip   short trip  
3          Fort Pierce      4.7          Meeting  short trip   short trip  
4      West Palm Beach     63.7   Customer Visit   long trip    long trip  
...                ...      ...              ...         ...          ...  
1151  Unknown Location      3.9   Temporary Site  short trip   short trip  
1152  Unknown Location     16.2          Meeting   long trip    long trip  
1153           Gampaha      6.4   Temporary Site   long trip  Medium trip  
1154         Ilukwatta     48.2   Temporary Site   long trip    long trip  
1155               NaN  12204.7              NaN   long trip    long trip  

[1156 rows x 9 columns]

In [58]:
df.groupby("START*")["MILES*"].agg("mean")
df.groupby("START*").mean()

MILES*
START*                     
Agnew              2.775000
Almond            15.200000
Apex               5.341176
Arabi             17.000000
Arlington          4.900000
...                     ...
West University    2.200000
Weston             4.000000
Westpark Place     2.182353
Whitebridge        4.020588
Winston Salem    133.600000

[177 rows x 1 columns]

In [59]:
df.groupby(["START*","STOP*"]).agg(["mean","sum"])

C:\Users\admin\AppData\Local\Temp\ipykernel_5600\1607901652.py:1: FutureWarning: ['START_DATE*', 'END_DATE*', 'CATEGORY*', 'PURPOSE*', 'MILES_cat', 'Miles_cat'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  df.groupby(["START*","STOP*"]).agg(["mean","sum"])


MILES*       
                                        mean    sum
START*        STOP*                                
Agnew         Agnew                 2.200000    2.2
              Cory                  4.300000    4.3
              Renaissance           2.300000    4.6
Almond        Bryson City          15.200000   15.2
Apex          Apex                  2.150000    4.3
...                                      ...    ...
Whitebridge   Wayne Ridge           7.975000   31.9
              Westpark Place        2.242857   31.4
              Whitebridge           2.014286   14.1
              Williamsburg Manor    8.300000    8.3
Winston Salem Asheville           133.600000  133.6

[363 rows x 2 columns]

In [60]:
df.groupby("START*").agg(["mean","sum"])

C:\Users\admin\AppData\Local\Temp\ipykernel_5600\3743653404.py:1: FutureWarning: ['START_DATE*', 'END_DATE*', 'CATEGORY*', 'STOP*', 'PURPOSE*', 'MILES_cat', 'Miles_cat'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  df.groupby("START*").agg(["mean","sum"])


MILES*       
                       mean    sum
START*                            
Agnew              2.775000   11.1
Almond            15.200000   15.2
Apex               5.341176   90.8
Arabi             17.000000   17.0
Arlington          4.900000    4.9
...                     ...    ...
West University    2.200000    4.4
Weston             4.000000    8.0
Westpark Place     2.182353   37.1
Whitebridge        4.020588  273.4
Winston Salem    133.600000  133.6

[177 rows x 2 columns]

In [61]:
df.tail()

START_DATE*         END_DATE* CATEGORY*            START*  \
1151  12/31/2016 13:24  12/31/2016 13:42  Business           Kar?chi   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1153  12/31/2016 21:32  12/31/2016 21:50  Business        Katunayake   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*        PURPOSE*   MILES_cat    Miles_cat  
1151  Unknown Location      3.9  Temporary Site  short trip   short trip  
1152  Unknown Location     16.2         Meeting   long trip    long trip  
1153           Gampaha      6.4  Temporary Site   long trip  Medium trip  
1154         Ilukwatta     48.2  Temporary Site   long trip    long trip  
1155               NaN  12204.7             NaN   long trip    long trip

In [62]:
df = df.iloc[:-1,:]

In [63]:
df.tail()

START_DATE*         END_DATE* CATEGORY*            START*  \
1150   12/31/2016 1:07   12/31/2016 1:14  Business           Kar?chi   
1151  12/31/2016 13:24  12/31/2016 13:42  Business           Kar?chi   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1153  12/31/2016 21:32  12/31/2016 21:50  Business        Katunayake   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   

                 STOP*  MILES*        PURPOSE*   MILES_cat    Miles_cat  
1150           Kar?chi     0.7         Meeting  short trip   short trip  
1151  Unknown Location     3.9  Temporary Site  short trip   short trip  
1152  Unknown Location    16.2         Meeting   long trip    long trip  
1153           Gampaha     6.4  Temporary Site   long trip  Medium trip  
1154         Ilukwatta    48.2  Temporary Site   long trip    long trip

In [66]:
df["START_DATE*"]= pd.to_datetime(df["START_DATE*"])
df.dtypes

C:\Users\admin\AppData\Local\Temp\ipykernel_5600\1787549802.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["START_DATE*"]= pd.to_datetime(df["START_DATE*"])


START_DATE*    datetime64[ns]
END_DATE*              object
CATEGORY*              object
START*                 object
STOP*                  object
MILES*                float64
PURPOSE*               object
MILES_cat              object
Miles_cat              object
dtype: object

In [93]:
res = df.groupby("START*").agg({"MILES*":["mean"],"START_DATE*":["min","max"]})

In [94]:
res
res.reset_index(inplace=True)
res.columns = ["START_CITY","AVG_DIST","EARLIEST_TR","RECENT_TR"]
res

START_CITY    AVG_DIST         EARLIEST_TR           RECENT_TR
0              Agnew    2.775000 2016-11-04 21:04:00 2016-11-06 10:50:00
1             Almond   15.200000 2016-10-30 12:58:00 2016-10-30 12:58:00
2               Apex    5.341176 2016-01-29 21:21:00 2016-12-12 14:26:00
3              Arabi   17.000000 2016-06-25 10:50:00 2016-06-25 10:50:00
4          Arlington    4.900000 2016-08-02 11:51:00 2016-08-02 11:51:00
..               ...         ...                 ...                 ...
172  West University    2.200000 2016-03-10 14:39:00 2016-03-16 18:43:00
173           Weston    4.000000 2016-03-05 12:57:00 2016-06-05 15:57:00
174   Westpark Place    2.182353 2016-02-26 11:05:00 2016-11-03 14:13:00
175      Whitebridge    4.020588 2016-01-19 09:09:00 2016-11-03 13:42:00
176    Winston Salem  133.600000 2016-10-28 18:13:00 2016-10-28 18:13:00

[177 rows x 4 columns]

In [95]:
res.to_csv("jay.csv")

In [103]:
import pandas as pd
store_sales = pd.read_csv("store_sales.csv")
store_sales.head()

store_id        city  Jan  Feb  Mar  Apr  May  Jun  July  Aug  Sep  Oct  \
0      S_1       Texas    8   20   13   21   17   20    24   17   16    9   
1      S_2  California   12   19   15   15   11   19     7   15   10   11   
2      S_3  California   16   16   14   19   23    6    13   13   15   14   
3      S_4       Texas    8   18   13   10   14   14     6    8    8   18   
4      S_5       Texas   19    5   24    9    5   24    10    5   24   15   

   Nov  Dec  
0    7    6  
1   21   19  
2   24    8  
3    7   11  
4    6   13

In [104]:
store_sales["Jan"].mean()
#store_sales.loc(["Jan"]).mean()

14.46

In [106]:
store_sales.apply("mean")
store_sales.apply("mean",axis = 1)

C:\Users\admin\AppData\Local\Temp\ipykernel_5600\3934536575.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  store_sales.apply("mean")
C:\Users\admin\AppData\Local\Temp\ipykernel_5600\3934536575.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  store_sales.apply("mean",axis = 1)


0     14.833333
1     14.500000
2     15.083333
3     11.250000
4     13.250000
        ...    
95    15.416667
96    12.833333
97    14.000000
98    14.416667
99    15.000000
Length: 100, dtype: float64

In [107]:
store_sales.apply("mean",axis = 0)

C:\Users\admin\AppData\Local\Temp\ipykernel_5600\2396841478.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  store_sales.apply("mean",axis = 0)


Jan     14.46
Feb     15.09
Mar     14.56
Apr     14.57
May     13.56
Jun     13.80
July    14.38
Aug     15.81
Sep     14.91
Oct     14.10
Nov     15.31
Dec     13.57
dtype: float64

In [108]:
store_sales.groupby("city").mean()

Jan        Feb        Mar        Apr        May        Jun  \
city                                                                           
Arizona     15.500000  15.272727  14.545455  14.954545  14.090909  15.090909   
California  14.744186  15.534884  14.627907  13.976744  13.255814  13.697674   
Texas       13.457143  14.428571  14.485714  15.057143  13.600000  13.114286   

                 July        Aug        Sep        Oct        Nov        Dec  
city                                                                          
Arizona     14.636364  15.500000  15.318182  14.954545  16.409091  13.318182  
California  14.813953  16.232558  14.883721  14.279070  15.279070  13.604651  
Texas       13.685714  15.485714  14.685714  13.342857  14.657143  13.685714

In [112]:
def bonus_func(sales_col,sales_no):
    elig_values = np.where(sales_col > sales_no,"eliglble","not eliglble")
    return elig_values
store_sales["Jan_bonus"]=bonus_func(store_sales["Jan"],10)

In [115]:
store_sales

store_id        city  Jan  Feb  Mar  Apr  May  Jun  July  Aug  Sep  Oct  \
0       S_1       Texas    8   20   13   21   17   20    24   17   16    9   
1       S_2  California   12   19   15   15   11   19     7   15   10   11   
2       S_3  California   16   16   14   19   23    6    13   13   15   14   
3       S_4       Texas    8   18   13   10   14   14     6    8    8   18   
4       S_5       Texas   19    5   24    9    5   24    10    5   24   15   
..      ...         ...  ...  ...  ...  ...  ...  ...   ...  ...  ...  ...   
95     S_96       Texas    7   10   20   20   10   15    15   21   15    7   
96     S_97  California   13    6    7   15   22   10    21   23   10    6   
97     S_98       Texas   16    9    6   14   20   13    11   10    8   22   
98     S_99     Arizona   18   16    9    5   12   22    11   13   21   17   
99    S_100  California    5   23   17   24   15   21    19   10   12   20   

    Nov  Dec     Jan_bonus  
0     7    6  not eliglble  
1    21   19      eliglble  
2    24    8      eliglble  
3     7   11  not eliglble  
4     6   13      eliglble  
..  ...  ...           ...  
95   23   22  not eliglble  
96   12    9      eliglble  
97   17   22      eliglble  
98   19   10      eliglble  
99    5    9  not eliglble  

[100 rows x 15 columns]

In [119]:
def bonus_func(sales_col):
    elig_values = np.where(sales_col > 10,"eliglble","not eliglble")
    return elig_values
newdf = store_sales.select_dtypes(include = ['int64','float64']).apply(bonus_func)
newdf

Jan           Feb           Mar           Apr           May  \
0   not eliglble      eliglble      eliglble      eliglble      eliglble   
1       eliglble      eliglble      eliglble      eliglble      eliglble   
2       eliglble      eliglble      eliglble      eliglble      eliglble   
3   not eliglble      eliglble      eliglble  not eliglble      eliglble   
4       eliglble  not eliglble      eliglble  not eliglble  not eliglble   
..           ...           ...           ...           ...           ...   
95  not eliglble  not eliglble      eliglble      eliglble  not eliglble   
96      eliglble  not eliglble  not eliglble      eliglble      eliglble   
97      eliglble  not eliglble  not eliglble      eliglble      eliglble   
98      eliglble      eliglble  not eliglble  not eliglble      eliglble   
99  not eliglble      eliglble      eliglble      eliglble      eliglble   

             Jun          July           Aug           Sep           Oct  \
0       eliglble      eliglble      eliglble      eliglble  not eliglble   
1       eliglble  not eliglble      eliglble  not eliglble      eliglble   
2   not eliglble      eliglble      eliglble      eliglble      eliglble   
3       eliglble  not eliglble  not eliglble  not eliglble      eliglble   
4       eliglble  not eliglble  not eliglble      eliglble      eliglble   
..           ...           ...           ...           ...           ...   
95      eliglble      eliglble      eliglble      eliglble  not eliglble   
96  not eliglble      eliglble      eliglble  not eliglble  not eliglble   
97      eliglble      eliglble  not eliglble  not eliglble      eliglble   
98      eliglble      eliglble      eliglble      eliglble      eliglble   
99      eliglble      eliglble  not eliglble      eliglble      eliglble   

             Nov           Dec  
0   not eliglble  not eliglble  
1       eliglble      eliglble  
2       eliglble  not eliglble  
3   not eliglble      eliglble  
4   not eliglble      eliglble  
..           ...           ...  
95      eliglble      eliglble  
96      eliglble  not eliglble  
97      eliglble      eliglble  
98      eliglble  not eliglble  
99  not eliglble  not eliglble  

[100 rows x 12 columns]

In [120]:
jay = pd.concat([store_sales,newdf])
jay.shape

(200, 15)

In [121]:
jay.tail()

store_id city           Jan           Feb           Mar           Apr  \
95      NaN  NaN  not eliglble  not eliglble      eliglble      eliglble   
96      NaN  NaN      eliglble  not eliglble  not eliglble      eliglble   
97      NaN  NaN      eliglble  not eliglble  not eliglble      eliglble   
98      NaN  NaN      eliglble      eliglble  not eliglble  not eliglble   
99      NaN  NaN  not eliglble      eliglble      eliglble      eliglble   

             May           Jun      July           Aug           Sep  \
95  not eliglble      eliglble  eliglble      eliglble      eliglble   
96      eliglble  not eliglble  eliglble      eliglble  not eliglble   
97      eliglble      eliglble  eliglble  not eliglble  not eliglble   
98      eliglble      eliglble  eliglble      eliglble      eliglble   
99      eliglble      eliglble  eliglble  not eliglble      eliglble   

             Oct           Nov           Dec Jan_bonus  
95  not eliglble      eliglble      eliglble       NaN  
96  not eliglble      eliglble  not eliglble       NaN  
97      eliglble      eliglble      eliglble       NaN  
98      eliglble      eliglble  not eliglble       NaN  
99      eliglble  not eliglble  not eliglble       NaN

In [122]:
jay = pd.concat([store_sales,newdf],axis=1)
jay

store_id        city  Jan  Feb  Mar  Apr  May  Jun July Aug  ...  \
0       S_1       Texas    8   20   13   21   17   20   24  17  ...   
1       S_2  California   12   19   15   15   11   19    7  15  ...   
2       S_3  California   16   16   14   19   23    6   13  13  ...   
3       S_4       Texas    8   18   13   10   14   14    6   8  ...   
4       S_5       Texas   19    5   24    9    5   24   10   5  ...   
..      ...         ...  ...  ...  ...  ...  ...  ...  ...  ..  ...   
95     S_96       Texas    7   10   20   20   10   15   15  21  ...   
96     S_97  California   13    6    7   15   22   10   21  23  ...   
97     S_98       Texas   16    9    6   14   20   13   11  10  ...   
98     S_99     Arizona   18   16    9    5   12   22   11  13  ...   
99    S_100  California    5   23   17   24   15   21   19  10  ...   

             Mar           Apr           May           Jun          July  \
0       eliglble      eliglble      eliglble      eliglble      eliglble   
1       eliglble      eliglble      eliglble      eliglble  not eliglble   
2       eliglble      eliglble      eliglble  not eliglble      eliglble   
3       eliglble  not eliglble      eliglble      eliglble  not eliglble   
4       eliglble  not eliglble  not eliglble      eliglble  not eliglble   
..           ...           ...           ...           ...           ...   
95      eliglble      eliglble  not eliglble      eliglble      eliglble   
96  not eliglble      eliglble      eliglble  not eliglble      eliglble   
97  not eliglble      eliglble      eliglble      eliglble      eliglble   
98  not eliglble  not eliglble      eliglble      eliglble      eliglble   
99      eliglble      eliglble      eliglble      eliglble      eliglble   

             Aug           Sep           Oct           Nov           Dec  
0       eliglble      eliglble  not eliglble  not eliglble  not eliglble  
1       eliglble  not eliglble      eliglble      eliglble      eliglble  
2       eliglble      eliglble      eliglble      eliglble  not eliglble  
3   not eliglble  not eliglble      eliglble  not eliglble      eliglble  
4   not eliglble      eliglble      eliglble  not eliglble      eliglble  
..           ...           ...           ...           ...           ...  
95      eliglble      eliglble  not eliglble      eliglble      eliglble  
96      eliglble  not eliglble  not eliglble      eliglble  not eliglble  
97  not eliglble  not eliglble      eliglble      eliglble      eliglble  
98      eliglble      eliglble      eliglble      eliglble  not eliglble  
99  not eliglble      eliglble      eliglble  not eliglble  not eliglble  

[100 rows x 27 columns]

In [20]:
dist = [45,5,5]
speed = [9,1,1]

In [21]:
time = dist/speed
time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [22]:
import numpy as np

In [23]:
dist = np.array(dist)
speed = np.array(speed)
time = dist/speed
time

array([5., 5., 5.])

In [4]:
f = np.array((1,2,3,4,5))
g = np.array((10,20,30,40,50))
f + g

array([11, 22, 33, 44, 55])

In [5]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [7]:
np.linspace(30,100,5) #(100-30)/(5-1) the distance of two number

array([ 30. ,  47.5,  65. ,  82.5, 100. ])

In [8]:
data = np.array((30,10,45,34,56,78,90,23,45,56,36,78))
data

array([30, 10, 45, 34, 56, 78, 90, 23, 45, 56, 36, 78])

In [12]:
data1 = data.reshape(4,3)
data1

array([[30, 10, 45],
       [34, 56, 78],
       [90, 23, 45],
       [56, 36, 78]])

In [13]:
even_data = (data % 2 == 0)
even_data

array([[ True,  True, False],
       [ True,  True,  True],
       [ True, False, False],
       [ True,  True,  True]])

In [14]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,5))+7

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [16]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.eye(5)    #identity matrix.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.diag((1,2,3,4))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])